# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8443acdd940fccc907e68c482886cc62ea7872e6d2d2222b82c8eecb7aa6568f94f472f54a85f8d8781f43e69c293a27d47d35a15649c3b78859df18066c3b1

test:
  secret_key_base: a17951eb6a504109c9b426918c503dfd4c6ce33bafffe1af1c58d3a8959a9db497aa7db6bff6830fd2b169b4320085573123f4cb371956a9afee70a1ac3e307f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
